[package]
name = "RustKey-service"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
serde = "1.0.228"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }
webauthn-rs="0.5.4"
tower-http = {version = "0.6.6", features = ["cors"] }